# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Insert your First Name', max_length=30)),
                ('last_name', models.CharField(help_text='Insert your Last Name', max_length=30)),
                ('email', models.EmailField(help_text='Insert a valid email address.', max_length=254)),
                ('password', models.CharField(help_text='Insert new password', max_length=24)),
            ],
        ),
    ]
